const lines = [
  "Walked the sewers of Paris.",
  "From now on boys this iron boat's your home.",
  "Away boys, away boys, heave away.",
  "Hanging out the window with a bottle full of rain.",
  "The moon in the window and a bird on the pole.",
  "We can always find a millionaire to shovel all the coal.",
  "A fifty-dollar bill inside a palladin's hat.",
  "Plays accordion for Mr. Weiss.",
  "Edna Million in a drop dead suit.",
  "Dutch Pink on a downtown train.",
  "I'm in the corner on the pouring rain.",
  "Two pairs of pants and a mohair vest.",
  "Across the stripes of a full moon's head.",
  "Flamingo drinking from a cocktail glass.",
  "All the hounds will start to roar.",
  "They drive along the pipeline, they tango 'til they're sore.",
  "They take apart their nightmares and they leave them by the door.",
  "Let me fall out of the window with confetti in my hair.",
  "Deal out Jacks or Better on a blanket by the stairs.",
  "Put my clarinet beneath your bed 'til I get back in town.",
  "Write my name on the hood, send me off to another town.",
  "Thunder that the rain makes when the shadow tops the hill.",
  "Well he's all boxed up on a red belle dame.",
  "A yellow bullet with a rag out in the wind.",
  "Got a wooden coat, this boy is never coming home.",
  "Cut through the canebrake, oh yeah.",
  "Broken glass, rusty nails where the wild violets grow.",
  "Say goodbye to the railroad, the mad dogs of summer.",
  "Go out to the meadow, the hills are a-green.",
  "Hush a wild violet, hush a band of gold.",
  "Well the smart money's on Harlow and the moon is in the street.",
  "And you're east of East Saint Louis and the wind is making speeches.",
  "And the rain sounds like a round of applause.",
  "And the band is going home, it's raining hammers, it's raining nails.",
  "And they all pretend they're orphans and their memory's like a train.",
  "Just dive right off the cars and splash into the street.",
  "Just like a stranger with the weeds in your heart.",
  "Splashing the wine with all the rain dogs.",
  "Taxi, we'd rather walk, huddle a doorway with the rain dogs.",
  "Oh how we danced and we swallowed the night.",
  "Beat out the dustman with the rain dogs.",
  "Give my umbrella to the rain dogs.",
  "And the moon's teeth marks are on the sky.",
  "And the steam comes out of the grill like the whole goddamn town's ready to blow.",
  "And you take on the dreams of the ones who have slept here.",
  "And I'm lost in the window, and I hide in the stairway.",
  "And I hang in the curtain, and I sleep in your hat.",
  "And no one brings anything small into a bar around here.",
  "With the clang and the thunder of the Southern Pacific going by.",
  "Til you're full of rag water and bitters and blue ruin.",
  "And you spill out over the side to anyone who will listen.",
  "Through the yellow windows of the evening train.",
  "With a pawnshop radio, quarter past four.",
  "Sitting in a sycamore in St. John's wood.",
  "Staying out of circulation 'til the dogs get tired.",
  "Never get up in the morning on a Saturday.",
  "And the Burlington Northern pulling out of the world.",
  "Now a head full of bourbon and a dream in the straw.",
  "Smuggled in a brand new pair of alligator shoes.",
  "Whizzin' on down in front of the East Coast.",
  "I don't care if they miss me, I never remember their names.",
  "Was whispered into the ear of Blind Jack Dawes.",
  "All Baker told the machine was that he never broke the law.",
  "Has punched a hole in the nighttime, yes.",
  "I'm shining like a new dime.",
  "They try so hard to break out of their little worlds.",
  "You wave your hand and they scatter like crows.",
  "They have nothing that will ever capture your heart.",
  "They're just thorns without the rose.",
  "I stand by the light at the four-way.",
  "They stay at the carnival, but they'll never win you back.",
  "With crows as big as airplanes.",
  "It rained mackerel it rained trout.",
  "I want to know am I the sky or a bird.",
  "We're chained to the world and we all gotta pull.",
  "A cheetah coat fills up with steam.",
  "With my rainy hammer and a heart that's true.",
  "They're lining up to mad dog your tilta whirl.",
  "Three shots for a dollar win a real live doll.",
  "Do you still leave nothing but bones in the way?",
  "Did you bury the carnival, lions and all?",
  "Are you still jumping out of windows in expensive clothes?",
  "They're dancing on the roof and the ceiling's coming down.",
  "I'm goin' out west where the wind blows tall.",
  "They got some money out there they're giving it away.",
  "I don't lose my composure in a high speed chase.",
  "One plays the violin and sleeps inside a fridge.",
  "Road kill has its seasons just like anything.",
  "It's possums in the autumn and it's farm cats in the spring.",
  "The woods will never tell what sleeps beneath the trees.",
  "Never leave a trace or forget a face.",
  "When the moon is a cold chiseled dagger.",
  "I've been as far as Mercy and Grand, frozen to the ground.",
  "The bus at the corner, the clock's on the wall.",
  "I'm stuck like a shipwreck out here in the dust.",
  "Sometimes the music from a dance will carry across the plains.",
  "Your pants, your shirt, your shoes. But not that feel.",
  "You can throw it out in the rain.",
  "You can always see it when you're coming into town.",
  "Once you hang it on the wall you can never take it down.",
  "I cross my wooden leg and I swear on my glass eye.",
];

var twline = lines[Math.floor(Math.random()*lines.length)];
document.addEventListener("DOMContentLoaded", () => {
  const placeholderElement = document.getElementById("tw-quote-placeholder");
  placeholderElement.textContent = twline;
});
